from __future__ import annotations

from pathlib import Path

REQUIRED = [
    "AGENTS.md",
    "Makefile",
    "configs/agent_workflow.yaml",
    "envs/core.yml",
    "docs/idea_bank.yml",
    "docs/project_brief.md",
    "docs/experiment_protocol.md",
    "results/claim_ledger.yml",
    "results/run_registry.yml",
    "workflows/snakemake/Snakefile",
]


def main() -> None:
    missing = [p for p in REQUIRED if not Path(p).exists()]
    write_reports(missing)
    if missing:
        raise SystemExit(f"Missing required reproducibility files: {missing}")
    print("reproducibility audit placeholder passed")


def write_reports(missing: list[str]) -> None:
    status = "failed" if missing else "passed"
    audit_lines = [
        "# Reproducibility audit",
        "",
        f"Status: {status}",
        "",
        "## Required files",
    ]
    for path in REQUIRED:
        marker = "missing" if path in missing else "present"
        audit_lines.append(f"- {path}: {marker}")
    audit_lines.extend(
        [
            "",
            "## Reviewer note",
            "This audit verifies required project scaffolding only. It does not validate scientific results.",
        ]
    )
    Path("docs/reproducibility_audit.md").write_text(
        "\n".join(audit_lines) + "\n", encoding="utf-8"
    )

    checklist_lines = [
        "# Submission checklist",
        "",
        "- [ ] Human approval of research question",
        "- [ ] Human approval of data sources and inclusion criteria",
        "- [ ] Human approval of experiment protocol",
        "- [ ] All verified claims have evidence paths",
        "- [ ] Citations are verified against paper cards and BibTeX",
        "- [ ] Figures are generated by code from data or results",
        "- [ ] Reproducibility audit passed",
        "- [ ] AI use is disclosed where required",
        "- [ ] Private or identifiable human data is excluded from Git",
    ]
    Path("docs/submission_checklist.md").write_text(
        "\n".join(checklist_lines) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
